development:
  omniauth:
    github:
      app_id: 91726ee4170d8e2679ec
      app_secret: 13c7e55e8e53c57a399181e96ea3a55a3fdd9c7c
    weibo:
      app_id:
      app_secret:
    qq:
      app_id:
      app_secret:
