default:
  host: localhost
  port: 6379
  compress: true
  expires_in: 8.hours
  compress_threshold: 32.kilobytes

development:
  db: 0
  namespace: store_development

test:
  db: 1
  namespace: store_test

production:
  db: 2
  host: 127.0.0.1
  namespace: store_production