# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b92de2b4f4e407ad08c8066ec1efe339537b51ad50d1619685443e852828e06bc17c8b6d8eb7bb8c4ae27eb1605997ec7af832993917bb516c47fec23f850f

test:
  secret_key_base: 6b8addffe7c4566b33f508823fdfc20386fcf932063dd56fc85589feadad24f341f008af18a609a90fdecb9c3304060b5b4d6bde99c095dd54dca355238da676

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
